# Generated by Django 4.0.3 on 2022-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
