# Generated by Django 4.0.3 on 2022-03-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0002_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
