# Generated by Django 4.0.3 on 2022-03-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0003_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rate',
            field=models.FloatField(),
        ),
    ]
